name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@2654679fe7f7c29875c669398a8ec0791b8a64a1 # v1.215.0
        with:
          bundler-cache: true

      - name: Run HTML Proofer tests
        run: bundle exec rake test

  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Ospack
        id: set-up-ospack
        uses: Ospack/actions/setup-ospack@master

      - name: Install vale
        run: ospack install vale

      - name: Run Vale linting on Markdown files
        run: vale --config="$(ospack --repo)"/.vale.ini _posts/

  check-redirects:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Check release notes redirect
        run: ruby ./.github/actions/check-redirects.rb
